version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'engage-db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
  app:
    build: .
    command: >
      bash -c "python3 manage.py migrate --no-input
      && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/engage
    ports:
      - "8000:8000"
    depends_on:
      - db
